"""Bundle the rendered PNGs into medal_art_pack.js for the tunic tool.

One entry per manifest key: {"d": base64 PNG, "aspect": w/h}. Run after
make_medals.py.

    python3 make_medals.py --dpi 300 --out out
    python3 make_pack.py --src out --out medal_art_pack.js
"""
import argparse
import base64
import json
import os

HEADER = ("// Generated by make_medals.py. Ribbon and medal artwork for "
          "cadet honours.\n"
          "// Sources and fidelity flags per key in medal_art_manifest.json.\n"
          "const MEDAL_ART = ")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--src", default="out")
    ap.add_argument("--out", default="medal_art_pack.js")
    a = ap.parse_args()

    manifest = json.load(open(f"{a.src}/medal_art_manifest.json"))
    pack = {}
    for key, entry in manifest.items():
        if key.startswith("_"):
            continue
        png = os.path.join(a.src, entry["png"])
        pack[key] = {"d": base64.b64encode(open(png, "rb").read()).decode(),
                     "aspect": entry["aspect"]}

    open(a.out, "w").write(HEADER + json.dumps(pack) + ";\n")
    size = os.path.getsize(a.out)
    print(f"wrote {len(pack)} keys to {a.out} ({size/1e6:.2f} MB)")


if __name__ == "__main__":
    main()
