"""badge_map.csv - the hand-maintained slug -> identity mapping.
Labels come from labels.py (Lt Beal's poster layout key), which is authoritative
over manifest.csv captions. NOT regenerated by extract_badges.py."""
import _paths  # noqa: F401  - chdir to repo root, expose data/
import json, csv, re, sys
from labels import LABELS, MISSING
sys.stdout.reconfigure(encoding="utf-8")

src = open("art/plate_pack.js", encoding="utf-8").read()
# each const is on its own line, so match per line - a DOTALL match here
# runs on into the NOT_EXTRACTED array that follows it
PLATE = json.loads(re.search(r"^const PLATE = (\[.*\]);$", src, re.M).group(1))

SLOT = {
 "rank":"right_rank_*", "appointment":"right_appointment", "star":"right_star_level",
 "marksmanship":"left_marksmanship", "first_aid":"left_proficiency_stack",
 "music":"left_proficiency_stack", "fitness":"left_proficiency_stack",
 "ctc":"right_ctc_grid", "shoulder":"*_corps_name / *_rcac_badge",
 "out_of_scope":"out_of_scope_*", "dofe":"", "terminated":"", "medal":"out_of_scope_medals",
 "heraldry":"", "not_a_badge":"", "unknown":"",
}
rows, unlabelled = [], []
for b in PLATE:
    hit = LABELS.get(b["slug"])
    if not hit and b.get("rec"):
        # recovered artwork carries its identity in the plate catalogue itself
        hit = (b.get("label",""), b["fam"], b.get("note",""))
    if not hit:
        unlabelled.append(b["slug"]); hit = ("", b["fam"], b["note"])
    label, fam, note = hit
    rows.append({"n":b["n"], "slug":b["slug"], "poster_caption":b["cap"], "label":label,
                 "family":fam, "slot":SLOT.get(fam,""), "aspect_trimmed":b["trim"],
                 "extracted": "recovered" if b.get("rec") else "yes", "note":note})
n = len(rows)
for i,(label,fam,note) in enumerate(MISSING, 1):
    rows.append({"n":f"M{i:02d}", "slug":"", "poster_caption":"", "label":label,
                 "family":fam, "slot":SLOT.get(fam,""), "aspect_trimmed":"",
                 "extracted":"NO", "note":note})

with open("data/badge_map.csv","w",newline="",encoding="utf-8") as f:
    w = csv.DictWriter(f, fieldnames=list(rows[0].keys())); w.writeheader(); w.writerows(rows)

from collections import Counter
print(f"badge_map.csv  {n} extracted + {len(MISSING)} known-missing = {len(rows)} rows")
if unlabelled: print("NO LABEL YET:", unlabelled)
print("\nby family (extracted / missing):")
ex = Counter(r["family"] for r in rows if r["extracted"]=="yes")
mi = Counter(r["family"] for r in rows if r["extracted"]=="NO")
for k in sorted(set(ex)|set(mi)):
    print(f"  {k:14} {ex.get(k,0):3} / {mi.get(k,0):<3}")
print("\nMISSING FROM THE EXTRACTION")
for r in rows:
    if r["extracted"]=="NO":
        print(f"  {r['n']} {r['label']:36} {r['family']:13} {r['note']}")
