"""Emit the art pack + catalogue for the badge identification sheet.

Rows 1-77 are the original extraction, in poster order. Their numbering is STABLE -
the plate's saved corrections key on it, so never renumber. Anything recovered from
a bad crop or a missed region is appended from 78 up.

Baseline labels come from labels.py (Lt Beal's poster layout key), not from the
manifest captions, which are unreliable."""
import _paths  # noqa: F401  - chdir to repo root, expose data/
import zipfile, io, csv, json, os, sys, base64, re, unicodedata
from PIL import Image
from labels import LABELS, MISSING
sys.stdout.reconfigure(encoding="utf-8")

MAXPX = 200

# Recovered artwork: bad crops that were split, and the region the extractor skipped.
RECOVERED = [
    ("art/recut/fit_bronze.png",     "Fitness – Bronze",     "fitness", "Missed region, recovered from the source PDF."),
    ("art/recut/fit_silver.png",     "Fitness – Silver",     "fitness", "Missed region, recovered from the source PDF."),
    ("art/recut/fit_gold.png",       "Fitness – Gold",       "fitness", "Missed region, recovered from the source PDF."),
    ("art/recut/fit_excellence.png", "Fitness – Excellence", "fitness", "Missed region, recovered from the source PDF."),
    ("art/recut/band0_col0.png",     "Music – Level 2",      "music",   "Split out of the unnamed_7 bad crop."),
    ("art/recut/band0_col1.png",     "Music – Level 3",      "music",   "Split out of the unnamed_7 bad crop."),
    ("art/recut/band0_col2.png",     "Music – Level 4",      "music",   "Split out of the unnamed_7 bad crop."),
    ("art/recut/corps_name_title__da_vi_d_d_e_f_al_ar_de.png",
     "Corps name title", "shoulder", "Split from item 15. Title = 1.923 x RCAC diameter wide."),
    ("art/recut/rcac_badge__da_vi_d_d_e_f_al_ar_de.png",
     "RCAC badge", "shoulder", "Split from item 15. A true circle; diameter still unmeasured."),
]

z = zipfile.ZipFile("rcac_badges.zip")
ZN = {unicodedata.normalize("NFC", n): n for n in z.namelist()}
def zread(name):
    n = unicodedata.normalize("NFC", name)
    if n in ZN: return z.read(ZN[n])
    stem = re.sub(r"[^a-z0-9_]", "", n.lower())
    for k, v in ZN.items():
        if re.sub(r"[^a-z0-9_]", "", k.lower()) == stem: return z.read(v)
    raise KeyError(name)

def pack(im):
    bb = im.getbbox()
    if bb: im = im.crop(bb)
    trim = round(im.width / im.height, 4) if im.height else 0
    sc = MAXPX / max(im.width, im.height)
    if sc < 1:
        im = im.resize((max(1, round(im.width*sc)), max(1, round(im.height*sc))), Image.LANCZOS)
    # WebP q90, not PNG - see the note in build_art.py. Every entry here is WebP,
    # so the mime lives in the page rather than per entry.
    buf = io.BytesIO(); im.save(buf, "WEBP", quality=90, method=4)
    return base64.b64encode(buf.getvalue()).decode(), trim

rows = list(csv.DictReader(open("data/manifest.csv", encoding="utf-8")))
rows.sort(key=lambda r: (round(float(r["y_pt"])/25), float(r["x_pt"])))

art, cat, unlabelled = {}, [], []
for i, r in enumerate(rows, 1):
    slug = r["slug"]
    d, trim = pack(Image.open(io.BytesIO(zread(r["png"]))).convert("RGBA"))
    art[slug] = d
    hit = LABELS.get(slug)
    if not hit: unlabelled.append(slug)
    label, fam, note = hit or ("", "unknown", "")
    cat.append({"n": i, "slug": slug, "cap": r["caption"], "x": float(r["x_pt"]),
                "y": float(r["y_pt"]), "crop": float(r["aspect"]), "trim": trim,
                "fam": fam, "label": label, "note": note, "rec": 0})

n = len(cat)
for path, label, fam, note in RECOVERED:
    if not os.path.exists(path):
        print("MISSING FILE:", path); continue
    n += 1
    key = "recut__" + os.path.splitext(os.path.basename(path))[0]
    d, trim = pack(Image.open(path).convert("RGBA"))
    art[key] = d
    cat.append({"n": n, "slug": key, "cap": "", "x": 0, "y": 0, "crop": trim, "trim": trim,
                "fam": fam, "label": label, "note": note, "rec": 1})

os.makedirs("art", exist_ok=True)
with open("art/plate_pack.js", "w", encoding="utf-8") as f:
    f.write("// Generated by build_plate.py. Crown copyright artwork, internal corps use.\n")
    f.write("const PLATE_ART = " + json.dumps(art, separators=(",", ":")) + ";\n")
    f.write("const PLATE = " + json.dumps(cat, ensure_ascii=False, separators=(",", ":")) + ";\n")
    f.write("const NOT_EXTRACTED = " + json.dumps(
        [{"label": l, "fam": f, "note": nt} for l, f, nt in MISSING],
        ensure_ascii=False, separators=(",", ":")) + ";\n")

from collections import Counter
mb = sum(len(v) for v in art.values()) / 1e6
print(f"{len(cat)} cards ({len(rows)} extracted + {len(cat)-len(rows)} recovered), {mb:.2f} MB")
print(f"{len(MISSING)} known-missing items listed separately")
if unlabelled: print("NO LABEL:", unlabelled)
for f_, c in Counter(x["fam"] for x in cat).most_common(): print(f"  {f_:14} {c}")
