#!/usr/bin/env python3
"""Re-encode the delivered medal pack from PNG to WebP.

`Medals and Ribbons/medal_art_pack.js` is authored in another session and arrives as
PNG. It is left untouched, because it is that session's artefact, and the optimised
copy is written to art/ with the rest of the generated packs. Same keys, same aspects,
about a third of the bytes.
"""
import _paths  # noqa: F401  - chdir to repo root
import base64
import io
import json
import os
import re
import sys

from PIL import Image

sys.stdout.reconfigure(encoding="utf-8")

SRC = "Medals and Ribbons/medal_art_pack.js"
OUT = os.path.join("art", "medal_pack.js")
ENTRY = re.compile(r'"([a-z0-9_]+)":\s*\{"d":\s*"([^"]+)",\s*"aspect":\s*([0-9.]+)\}')


def main():
    if not os.path.exists(SRC):
        print(f"missing {SRC} - medals will draw as placeholders")
        return 0

    items = ENTRY.findall(open(SRC, encoding="utf-8").read())
    if not items:
        sys.exit("no entries parsed - has the pack format changed?")

    art, before, after = {}, 0, 0
    for key, d, aspect in items:
        png = base64.b64decode(d)
        before += len(png)
        im = Image.open(io.BytesIO(png)).convert("RGBA")
        buf = io.BytesIO()
        im.save(buf, "WEBP", quality=90, method=4)
        after += len(buf.getvalue())
        art[key] = {"d": base64.b64encode(buf.getvalue()).decode(),
                    "aspect": float(aspect), "m": "image/webp"}

    os.makedirs("art", exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as f:
        f.write("// Generated by repack_medals.py. Do not edit; edit the source pack.\n")
        f.write("const MEDAL_ART = " + json.dumps(art, separators=(",", ":")) + ";\n")

    print(f"{len(art)} medals repacked  {before/1e6:.2f} MB PNG -> "
          f"{after/1e6:.2f} MB WebP ({after/before*100:.0f}%)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
